#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Figure8_ADNI_longitudinal_delta_cBAG_STRICT.py
==============================================

ADNI-only longitudinal Figure 8 using strict exact column mapping.

Inputs
------
1) OOF cBAG source:
   /mnt/newStor/paros/paros_WORK/ines/results/
     BrainAgePredictionADNI_stratified_groupcv_targetnorm_bagbiascorr_oofglobal/
       ablation_<feature_set>/validation_figures_oof/subject_level_validation_input.csv

2) Enriched endpoint source generated by Figure 4 enrichment:
   /mnt/newStor/paros/paros_WORK/ines/results/
     BrainAgePredictionADNI_stratified_groupcv_targetnorm_bagbiascorr_oofglobal/
       ablation_<feature_set>/validation_figures_full_cohort/
         subject_level_validation_input_enriched_for_Figure4.csv

Design
------
- Use ADNI only.
- Use OOF cBAG for the longitudinal brain-age delta.
- Use exact curated endpoint columns from the enriched Figure 4 table.
- No keyword fallback.
- Drop endpoints with insufficient paired deltas or zero variance.
- Pair visits by Subject_ID pattern: R####_y0 and R####_y4.

Outputs
-------
<base-dir>/Figure8_ADNI_longitudinal_delta_cBAG_STRICT/
    Figure8_ADNI_longitudinal_delta_cBAG_STRICT.png/pdf
    Supplementary_Figure8_ADNI_longitudinal_delta_cBAG_STRICT.png/pdf
    adni_longitudinal_delta_subject_table.csv
    adni_longitudinal_delta_association_stats.csv
    adni_longitudinal_endpoint_availability.csv
    figure8_adni_manifest.csv
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import pearsonr, spearmanr


RESULTS_ROOT = Path("/mnt/newStor/paros/paros_WORK/ines/results")
ADNI_DIR = "BrainAgePredictionADNI_stratified_groupcv_targetnorm_bagbiascorr_oofglobal"
BASE_DIR = RESULTS_ROOT / "BrainAgeValidation_AllCohorts_BAGBiasCorr_OOFGlobal_BiologicalValidation"

SENTINELS = {
    -999999, -99999, -9999, -999,
    -888888, -88888, -8888, -888,
    -777777, -77777, -7777, -777,
    999, 9999, 99999, 999999,
    888, 8888, 88888, 888888,
    777, 7777, 77777, 777777,
}

CBAG_PRIORITY = [
    "cBAG_oof_global_raw_clean",
    "cBAG_oof_global",
    "cBAG_global_raw_clean",
    "cBAG_global",
    "cBAG_raw_clean",
    "cBAG",
]

# Exact, strict endpoint mapping. No fallback.
ENDPOINTS: Dict[str, Dict[str, str]] = {
    "Cognition composite": {
        "column": "cognition_composite_raw_clean",
        "domain": "Clinical",
    },
    "MMSE": {
        "column": "MMSE_total_raw_clean",
        "domain": "Clinical",
    },
    "MoCA": {
        "column": "MOCA_total_corrected_raw_clean",
        "domain": "Clinical",
    },
    "ADAS": {
        "column": "ADAS_total_raw_clean",
        "domain": "Clinical",
    },
    "Hippocampal volume (mm³)": {
        "column": "Hc_volume_mm3",
        "domain": "Structural MRI",
    },
    "Hippocampal volume (% brain)": {
        "column": "Hc_volume_pct_brain",
        "domain": "Structural MRI",
    },
    "Hippocampal FA": {
        "column": "Hc_FA",
        "domain": "Diffusion MRI",
    },
    "Hippocampal RD": {
        "column": "Hc_RD",
        "domain": "Diffusion MRI",
    },
    "Hippocampal AD": {
        "column": "Hc_AD",
        "domain": "Diffusion MRI",
    },
    "Hippocampal ADC": {
        "column": "Hc_ADC",
        "domain": "Diffusion MRI",
    },
    "Total brain volume": {
        "column": "Total_Brain_volume",
        "domain": "Structural MRI",
    },
    "Total brain FA": {
        "column": "Total_Brain_FA",
        "domain": "Diffusion MRI",
    },
    "Graph clustering": {
        "column": "Clustering_Coeff_raw_clean",
        "domain": "Network",
    },
    "Graph path length": {
        "column": "Path_Length_raw_clean",
        "domain": "Network",
    },
    "Global efficiency": {
        "column": "Global_Efficiency_raw_clean",
        "domain": "Network",
    },
    "Local efficiency": {
        "column": "Local_Efficiency_raw_clean",
        "domain": "Network",
    },
    "BMI": {
        "column": "BMI_raw_clean",
        "domain": "Vascular/metabolic",
    },
    "BMI calculated": {
        "column": "BMI_calculated_raw_clean",
        "domain": "Vascular/metabolic",
    },
    "PHC BMI": {
        "column": "PHC_BMI",
        "domain": "Vascular/metabolic",
    },
}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Build ADNI-only strict longitudinal Figure 8.")
    p.add_argument("--results-root", default=str(RESULTS_ROOT))
    p.add_argument("--base-dir", default=str(BASE_DIR))
    p.add_argument("--feature-set", default="imaging_only")
    p.add_argument("--outdir", default=None)
    p.add_argument("--formats", default="png,pdf")
    p.add_argument("--dpi", type=int, default=450)
    p.add_argument("--min-n", type=int, default=12)
    p.add_argument("--corr-method", default="pearson", choices=["pearson", "spearman"])
    p.add_argument("--main-endpoints", default="Cognition composite,Hippocampal volume (mm³),Hippocampal FA,Total brain volume,Total brain FA,Global efficiency")
    p.add_argument("--max-forest-endpoints", type=int, default=14)
    return p.parse_args()


def clean_numeric(x) -> pd.Series:
    s = pd.to_numeric(x, errors="coerce")
    for v in SENTINELS:
        s = s.mask(s == v, np.nan)
    return s.replace([np.inf, -np.inf], np.nan)


def parse_subject_visit(x) -> Tuple[str, int | None]:
    s = str(x).strip()
    m = re.match(r"^(.+?)_y(\d+)$", s, flags=re.I)
    if m:
        return m.group(1).upper(), int(m.group(2))
    return s.upper(), None


def first_existing(df: pd.DataFrame, candidates: List[str]) -> str | None:
    for c in candidates:
        if c in df.columns:
            return c
    return None


def load_oof_cbag(results_root: Path, feature_set: str) -> Tuple[pd.DataFrame, str]:
    path = (
        results_root / ADNI_DIR / f"ablation_{feature_set}"
        / "validation_figures_oof" / "subject_level_validation_input.csv"
    )
    if not path.exists():
        raise FileNotFoundError(path)

    df = pd.read_csv(path, low_memory=False)
    id_col = first_existing(df, ["Subject_ID", "graph_id", "connectome_key", "subject_id", "ID"])
    if id_col is None:
        raise ValueError(f"No usable ID column in OOF file: {path}")

    cbag_col = first_existing(df, CBAG_PRIORITY)
    if cbag_col is None:
        raise ValueError(f"No usable cBAG column in OOF file: {path}")

    parsed = df[id_col].apply(parse_subject_visit)
    out = pd.DataFrame({
        "scan_id": df[id_col].astype(str),
        "subject_base": parsed.apply(lambda z: z[0]),
        "visit": parsed.apply(lambda z: z[1]),
        "oof_cbag": clean_numeric(df[cbag_col]),
        "oof_id_col": id_col,
        "oof_cbag_col": cbag_col,
    })
    out = out[out["visit"].notna()].copy()
    out["visit"] = out["visit"].astype(int)

    # Collapse accidental duplicates per scan.
    out = (
        out.sort_values(["subject_base", "visit"])
           .groupby(["subject_base", "visit"], as_index=False)
           .first()
    )

    return out, str(path)


def load_enriched_endpoints(results_root: Path, feature_set: str) -> Tuple[pd.DataFrame, str]:
    path = (
        results_root / ADNI_DIR / f"ablation_{feature_set}"
        / "validation_figures_full_cohort"
        / "subject_level_validation_input_enriched_for_Figure4.csv"
    )
    if not path.exists():
        raise FileNotFoundError(path)

    df = pd.read_csv(path, low_memory=False)
    id_col = first_existing(df, ["Subject_ID", "graph_id", "connectome_key", "subject_id", "ID"])
    if id_col is None:
        raise ValueError(f"No usable ID column in enriched file: {path}")

    parsed = df[id_col].apply(parse_subject_visit)
    out = df.copy()
    out["subject_base"] = parsed.apply(lambda z: z[0])
    out["visit"] = parsed.apply(lambda z: z[1])
    out = out[out["visit"].notna()].copy()
    out["visit"] = out["visit"].astype(int)

    keep_cols = ["subject_base", "visit", id_col]
    for spec in ENDPOINTS.values():
        c = spec["column"]
        if c in out.columns and c not in keep_cols:
            keep_cols.append(c)

    # Include raw columns needed for traceability if present.
    out = out[keep_cols].copy()
    out = (
        out.sort_values(["subject_base", "visit"])
           .groupby(["subject_base", "visit"], as_index=False)
           .first()
    )

    return out, str(path)


def make_delta_table(oof: pd.DataFrame, endpoints: pd.DataFrame) -> pd.DataFrame:
    merged = oof.merge(
        endpoints,
        on=["subject_base", "visit"],
        how="inner",
        suffixes=("", "_endpoint"),
    )

    rows = []
    for subject, g in merged.groupby("subject_base"):
        if g["visit"].nunique() < 2:
            continue

        g = g.sort_values("visit")
        first = g.iloc[0]
        last = g.iloc[-1]

        if pd.isna(first["oof_cbag"]) or pd.isna(last["oof_cbag"]):
            continue

        row = {
            "cohort": "ADNI",
            "subject_base": subject,
            "baseline_visit": int(first["visit"]),
            "followup_visit": int(last["visit"]),
            "delta_visit": int(last["visit"] - first["visit"]),
            "baseline_cbag_oof": first["oof_cbag"],
            "followup_cbag_oof": last["oof_cbag"],
            "delta_cbag_oof": last["oof_cbag"] - first["oof_cbag"],
            "oof_cbag_col": first["oof_cbag_col"],
        }

        for endpoint, spec in ENDPOINTS.items():
            col = spec["column"]
            row[f"{endpoint}__column"] = col
            if col not in g.columns:
                row[f"baseline__{endpoint}"] = np.nan
                row[f"followup__{endpoint}"] = np.nan
                row[f"delta__{endpoint}"] = np.nan
                continue

            b = clean_numeric(pd.Series([first[col]])).iloc[0]
            f = clean_numeric(pd.Series([last[col]])).iloc[0]
            row[f"baseline__{endpoint}"] = b
            row[f"followup__{endpoint}"] = f
            row[f"delta__{endpoint}"] = f - b if pd.notna(b) and pd.notna(f) else np.nan

        rows.append(row)

    return pd.DataFrame(rows)


def fisher_ci(r: float, n: int) -> Tuple[float, float]:
    if pd.isna(r) or n <= 3:
        return np.nan, np.nan
    rr = float(np.clip(r, -0.999999, 0.999999))
    z = np.arctanh(rr)
    se = 1.0 / math.sqrt(n - 3)
    return float(np.tanh(z - 1.96 * se)), float(np.tanh(z + 1.96 * se))


def corr_stats(x: pd.Series, y: pd.Series, method: str) -> dict:
    x = clean_numeric(x)
    y = clean_numeric(y)
    ok = x.notna() & y.notna()
    n = int(ok.sum())

    if n < 3 or x[ok].nunique() < 2 or y[ok].nunique() < 2:
        return {"n": n, "r": np.nan, "p": np.nan, "ci_low": np.nan, "ci_high": np.nan}

    if method == "spearman":
        r, p = spearmanr(x[ok], y[ok])
    else:
        r, p = pearsonr(x[ok], y[ok])

    lo, hi = fisher_ci(float(r), n)
    return {"n": n, "r": float(r), "p": float(p), "ci_low": lo, "ci_high": hi}


def compute_associations(delta: pd.DataFrame, min_n: int, method: str) -> Tuple[pd.DataFrame, pd.DataFrame]:
    availability_rows = []
    stat_rows = []

    for endpoint, spec in ENDPOINTS.items():
        delta_col = f"delta__{endpoint}"
        source_col = spec["column"]
        domain = spec["domain"]

        if delta_col not in delta.columns:
            availability_rows.append({
                "endpoint": endpoint,
                "domain": domain,
                "source_column": source_col,
                "source_column_present": False,
                "n_delta": 0,
                "sd_delta": np.nan,
                "n_unique_delta": 0,
                "usable": False,
                "reason": "missing_delta_column",
            })
            continue

        y = clean_numeric(delta[delta_col])
        n = int(y.notna().sum())
        sd = float(y.std()) if n > 1 else np.nan
        n_unique = int(y.nunique(dropna=True))

        usable = bool(n >= min_n and n_unique >= 2 and np.isfinite(sd) and sd > 0)
        reason = "ok" if usable else "insufficient_n_or_zero_variance"

        availability_rows.append({
            "endpoint": endpoint,
            "domain": domain,
            "source_column": source_col,
            "source_column_present": True,
            "n_delta": n,
            "sd_delta": sd,
            "n_unique_delta": n_unique,
            "usable": usable,
            "reason": reason,
        })

        if usable:
            stats = corr_stats(delta["delta_cbag_oof"], delta[delta_col], method)
            status = "ok" if stats["n"] >= min_n and pd.notna(stats["r"]) else "insufficient_n_or_variance"
        else:
            stats = {"n": n, "r": np.nan, "p": np.nan, "ci_low": np.nan, "ci_high": np.nan}
            status = reason

        stat_rows.append({
            "endpoint": endpoint,
            "domain": domain,
            "source_column": source_col,
            "delta_column": delta_col,
            **stats,
            "status": status,
            "abs_r": abs(stats["r"]) if pd.notna(stats["r"]) else np.nan,
        })

    return pd.DataFrame(stat_rows), pd.DataFrame(availability_rows)


def panel_label(ax, letter: str):
    ax.text(-0.12, 1.08, letter, transform=ax.transAxes, fontsize=15, fontweight="bold", va="top", ha="left")


def scatter_panel(ax, delta: pd.DataFrame, stats: pd.DataFrame, endpoint: str):
    col = f"delta__{endpoint}"
    if col not in delta.columns:
        ax.text(0.5, 0.5, f"{endpoint}\nnot available", ha="center", va="center")
        ax.axis("off")
        return

    x = clean_numeric(delta["delta_cbag_oof"])
    y = clean_numeric(delta[col])
    ok = x.notna() & y.notna()

    if ok.sum() < 3 or x[ok].nunique() < 2 or y[ok].nunique() < 2:
        ax.text(0.5, 0.5, f"{endpoint}\ninsufficient longitudinal variation", ha="center", va="center")
        ax.axis("off")
        return

    ax.scatter(x[ok], y[ok], s=26, alpha=0.75, edgecolor="black", linewidth=0.25)

    coef = np.polyfit(x[ok], y[ok], 1)
    xx = np.linspace(float(x[ok].min()), float(x[ok].max()), 100)
    ax.plot(xx, coef[0] * xx + coef[1], linestyle="--", linewidth=1.2)

    row = stats[stats["endpoint"] == endpoint]
    subtitle = ""
    if not row.empty and pd.notna(row.iloc[0]["r"]):
        r = row.iloc[0]["r"]
        p = row.iloc[0]["p"]
        n = int(row.iloc[0]["n"])
        subtitle = f"n={n}, r={r:.2f}, p={p:.2g}"

    ax.axvline(0, linewidth=0.8, alpha=0.6)
    ax.axhline(0, linewidth=0.8, alpha=0.6)
    ax.grid(True, alpha=0.25)
    ax.set_xlabel("ΔcBAG OOF")
    ax.set_ylabel(f"Δ{endpoint}")
    ax.set_title(f"ΔcBAG vs Δ{endpoint}\n{subtitle}", fontsize=10)


def distribution_panel(ax, delta: pd.DataFrame):
    x = clean_numeric(delta["delta_cbag_oof"]).dropna()
    ax.hist(x, bins=18, alpha=0.8)
    ax.axvline(0, linewidth=1)
    ax.set_xlabel("ΔcBAG OOF")
    ax.set_ylabel("Subjects")
    ax.set_title(f"ADNI longitudinal ΔcBAG\nn={len(x)}, y{int(delta['baseline_visit'].min())}→y{int(delta['followup_visit'].max())}")
    ax.grid(True, axis="y", alpha=0.25)


def forest_panel(ax, stats: pd.DataFrame, endpoints: List[str]):
    rows = stats[(stats["endpoint"].isin(endpoints)) & (stats["status"] == "ok")].copy()
    if rows.empty:
        ax.text(0.5, 0.5, "No usable associations", ha="center", va="center")
        ax.axis("off")
        return

    rows["endpoint"] = pd.Categorical(rows["endpoint"], categories=endpoints, ordered=True)
    rows = rows.sort_values("endpoint")
    y = np.arange(len(rows))

    for i, (_, r) in enumerate(rows.iterrows()):
        if pd.notna(r["ci_low"]) and pd.notna(r["ci_high"]):
            ax.plot([r["ci_low"], r["ci_high"]], [i, i], linewidth=1.2)
        ax.scatter(r["r"], i, s=55, edgecolor="black", linewidth=0.3)
        ax.text(1.03, i, f"n={int(r['n'])}, p={r['p']:.2g}", va="center", fontsize=8)

    ax.axvline(0, linewidth=1)
    ax.set_yticks(y)
    ax.set_yticklabels(rows["endpoint"].tolist(), fontsize=8)
    ax.invert_yaxis()
    ax.set_xlim(-1, 1)
    ax.set_xlabel("Correlation r: ΔcBAG OOF vs Δendpoint")
    ax.set_title("ADNI longitudinal association summary")
    ax.grid(True, axis="x", alpha=0.25)


def availability_heatmap(ax, availability: pd.DataFrame):
    rows = availability.copy()
    rows = rows.sort_values(["usable", "n_delta"], ascending=[False, False])
    labels = rows["endpoint"].tolist()
    vals = rows[["n_delta", "n_unique_delta"]].to_numpy(dtype=float)

    im = ax.imshow(vals, aspect="auto")
    ax.set_xticks([0, 1])
    ax.set_xticklabels(["N paired", "N unique Δ"])
    ax.set_yticks(np.arange(len(labels)))
    ax.set_yticklabels(labels, fontsize=7)

    for i in range(vals.shape[0]):
        for j in range(vals.shape[1]):
            ax.text(j, i, f"{int(vals[i, j])}", ha="center", va="center", fontsize=7)

    ax.set_title("Endpoint longitudinal availability")
    cb = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cb.set_label("Count")


def endpoint_delta_boxplot(ax, delta: pd.DataFrame, endpoints: List[str]):
    data = []
    labels = []
    for e in endpoints:
        col = f"delta__{e}"
        if col not in delta.columns:
            continue
        y = clean_numeric(delta[col]).dropna()
        if len(y) >= 3 and y.nunique() >= 2:
            data.append(y.values)
            labels.append(e)

    if not data:
        ax.text(0.5, 0.5, "No endpoint deltas", ha="center", va="center")
        ax.axis("off")
        return

    ax.boxplot(data, labels=labels, vert=False, showfliers=False)
    ax.axvline(0, linewidth=1)
    ax.tick_params(axis="y", labelsize=7)
    ax.set_title("Endpoint Δ distributions")
    ax.grid(True, axis="x", alpha=0.25)


def save_fig(fig, outbase: Path, formats: List[str], dpi: int) -> List[str]:
    saved = []
    for fmt in formats:
        p = outbase.with_suffix(f".{fmt}")
        fig.savefig(p, dpi=dpi, bbox_inches="tight")
        saved.append(str(p))
    plt.close(fig)
    return saved


def make_main_figure(delta: pd.DataFrame, stats: pd.DataFrame, availability: pd.DataFrame,
                     main_endpoints: List[str], outdir: Path, formats: List[str], dpi: int) -> List[str]:
    usable = set(availability.loc[availability["usable"], "endpoint"])
    main = [e for e in main_endpoints if e in usable]

    if len(main) < 5:
        extra = (
            stats[stats["status"] == "ok"]
            .sort_values(["abs_r", "n"], ascending=[False, False])["endpoint"]
            .tolist()
        )
        for e in extra:
            if e not in main:
                main.append(e)
            if len(main) >= 5:
                break

    # Need five scatter panels for 2x3 layout after distribution.
    while len(main) < 5:
        main.append("__missing__")

    fig, axes = plt.subplots(2, 3, figsize=(17, 10.5))
    ax = axes.ravel()

    distribution_panel(ax[0], delta)
    panel_label(ax[0], "A")

    for i in range(1, 5):
        endpoint = main[i - 1]
        if endpoint == "__missing__":
            ax[i].text(0.5, 0.5, "No additional usable endpoint", ha="center", va="center")
            ax[i].axis("off")
        else:
            scatter_panel(ax[i], delta, stats, endpoint)
        panel_label(ax[i], chr(ord("A") + i))

    forest_endpoints = [e for e in main if e != "__missing__"]
    # Add more endpoints for forest if available.
    ranked = stats[stats["status"] == "ok"].sort_values(["abs_r", "n"], ascending=[False, False])["endpoint"].tolist()
    for e in ranked:
        if e not in forest_endpoints:
            forest_endpoints.append(e)
        if len(forest_endpoints) >= 12:
            break

    forest_panel(ax[5], stats, forest_endpoints)
    panel_label(ax[5], "F")

    fig.suptitle("Figure 8. ADNI longitudinal change in OOF cBAG and biological endpoints", fontsize=15, y=0.995)
    fig.tight_layout(rect=[0, 0, 1, 0.97])

    return save_fig(fig, outdir / "Figure8_ADNI_longitudinal_delta_cBAG_STRICT", formats, dpi)


def make_supp_figure(delta: pd.DataFrame, stats: pd.DataFrame, availability: pd.DataFrame,
                     outdir: Path, formats: List[str], dpi: int, max_forest: int) -> List[str]:
    fig, axes = plt.subplots(2, 2, figsize=(16.5, 12))
    ax = axes.ravel()

    availability_heatmap(ax[0], availability)
    panel_label(ax[0], "A")

    ranked = stats[stats["status"] == "ok"].sort_values(["abs_r", "n"], ascending=[False, False])["endpoint"].tolist()
    forest_endpoints = ranked[:max_forest]
    forest_panel(ax[1], stats, forest_endpoints)
    panel_label(ax[1], "B")

    endpoint_delta_boxplot(ax[2], delta, forest_endpoints[:10])
    panel_label(ax[2], "C")

    # p-value/effect summary scatter
    ok = stats[stats["status"] == "ok"].copy()
    if ok.empty:
        ax[3].text(0.5, 0.5, "No usable associations", ha="center", va="center")
        ax[3].axis("off")
    else:
        ok["neglog10p"] = -np.log10(ok["p"].clip(lower=1e-300))
        ax[3].scatter(ok["r"], ok["neglog10p"], s=60, alpha=0.8, edgecolor="black", linewidth=0.3)
        for _, r in ok.iterrows():
            ax[3].text(r["r"], r["neglog10p"], r["endpoint"], fontsize=7, ha="left", va="bottom")
        ax[3].axvline(0, linewidth=1)
        ax[3].set_xlabel("Correlation r")
        ax[3].set_ylabel("-log10(p)")
        ax[3].set_title("Effect size and nominal significance")
        ax[3].grid(True, alpha=0.25)
    panel_label(ax[3], "D")

    fig.suptitle("Supplementary Figure 8. ADNI longitudinal endpoint availability and associations", fontsize=15, y=0.995)
    fig.tight_layout(rect=[0, 0, 1, 0.97])

    return save_fig(fig, outdir / "Supplementary_Figure8_ADNI_longitudinal_delta_cBAG_STRICT", formats, dpi)


def main() -> None:
    args = parse_args()

    results_root = Path(args.results_root).expanduser().resolve()
    base_dir = Path(args.base_dir).expanduser().resolve()
    outdir = Path(args.outdir).expanduser().resolve() if args.outdir else base_dir / "Figure8_ADNI_longitudinal_delta_cBAG_STRICT"
    outdir.mkdir(parents=True, exist_ok=True)

    formats = [f.strip().lower().lstrip(".") for f in args.formats.split(",") if f.strip()]
    main_endpoints = [x.strip() for x in args.main_endpoints.split(",") if x.strip()]

    print("=" * 100)
    print("Figure 8 ADNI-only STRICT longitudinal delta-cBAG")
    print("=" * 100)
    print("RESULTS_ROOT:", results_root)
    print("BASE_DIR:", base_dir)
    print("OUTDIR:", outdir)
    print("FEATURE_SET:", args.feature_set)
    print("MIN_N:", args.min_n)
    print("CORR_METHOD:", args.corr_method)

    oof, oof_path = load_oof_cbag(results_root, args.feature_set)
    endpoints, endpoint_path = load_enriched_endpoints(results_root, args.feature_set)

    print("\nInput files:")
    print("OOF:", oof_path)
    print("ENRICHED:", endpoint_path)
    print("\nOOF scan rows:", len(oof))
    print("Endpoint scan rows:", len(endpoints))

    delta = make_delta_table(oof, endpoints)
    if delta.empty:
        raise SystemExit("No ADNI longitudinal pairs found after merging OOF cBAG and enriched endpoints.")

    stats, availability = compute_associations(delta, min_n=args.min_n, method=args.corr_method)

    delta_path = outdir / "adni_longitudinal_delta_subject_table.csv"
    stats_path = outdir / "adni_longitudinal_delta_association_stats.csv"
    avail_path = outdir / "adni_longitudinal_endpoint_availability.csv"

    delta.to_csv(delta_path, index=False)
    stats.to_csv(stats_path, index=False)
    availability.to_csv(avail_path, index=False)

    print("\nDelta table:")
    print("subjects:", len(delta))
    print(delta[["subject_base", "baseline_visit", "followup_visit", "delta_cbag_oof"]].head().to_string(index=False))

    print("\nEndpoint availability:")
    print(availability.to_string(index=False))

    print("\nAssociations:")
    print(stats.sort_values(["status", "abs_r"], ascending=[True, False]).to_string(index=False))

    main_outputs = make_main_figure(delta, stats, availability, main_endpoints, outdir, formats, args.dpi)
    supp_outputs = make_supp_figure(delta, stats, availability, outdir, formats, args.dpi, args.max_forest_endpoints)

    manifest = pd.DataFrame([
        {
            "figure": "Figure 8",
            "cohort": "ADNI",
            "feature_set": args.feature_set,
            "cbag_source": oof_path,
            "endpoint_source": endpoint_path,
            "delta_subject_table": str(delta_path),
            "association_stats": str(stats_path),
            "availability": str(avail_path),
            "outputs": ";".join(main_outputs),
            "note": "ADNI-only strict longitudinal analysis; HABS excluded because current HABS prediction outputs contain no paired y0/y2 subjects.",
        },
        {
            "figure": "Supplementary Figure 8",
            "cohort": "ADNI",
            "feature_set": args.feature_set,
            "cbag_source": oof_path,
            "endpoint_source": endpoint_path,
            "delta_subject_table": str(delta_path),
            "association_stats": str(stats_path),
            "availability": str(avail_path),
            "outputs": ";".join(supp_outputs),
            "note": "Endpoint availability and expanded association summary.",
        },
    ])
    manifest_path = outdir / "figure8_adni_manifest.csv"
    manifest.to_csv(manifest_path, index=False)

    print("\nSaved outputs:")
    for p in main_outputs + supp_outputs:
        print(p)
    print("\nSaved tables:")
    print(delta_path)
    print(stats_path)
    print(avail_path)
    print(manifest_path)
    print("\nDONE")


if __name__ == "__main__":
    main()
